name: Deploy to Railway

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run tests
      run: |
        python -m pytest tests/ || echo "No tests yet"
    
    - name: Deploy to Railway
      if: secrets.RAILWAY_TOKEN != null
      uses: bervProject/railway-deploy@main
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      with:
        service: life-management
        
    - name: Railway deployment skipped
      if: secrets.RAILWAY_TOKEN == null
      run: echo "Railway token not configured, skipping deployment"