name: Deploy to Railway

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run tests
      run: |
        python -m pytest tests/ || echo "No tests yet"
    
    - name: Check Railway token
      id: check-token
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      run: |
        if [ -z "$RAILWAY_TOKEN" ]; then
          echo "has_token=false" >> $GITHUB_OUTPUT
        else
          echo "has_token=true" >> $GITHUB_OUTPUT
        fi
    
    - name: Install Railway CLI
      if: steps.check-token.outputs.has_token == 'true'
      run: |
        npm install -g @railway/cli
        
    - name: Deploy to Railway
      if: steps.check-token.outputs.has_token == 'true'
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      run: |
        echo "Using Railway CLI for deployment..."
        railway login --token $RAILWAY_TOKEN
        railway deploy --service life-management || railway deploy
        
    - name: Railway deployment skipped
      if: steps.check-token.outputs.has_token == 'false'
      run: echo "Railway token not configured, skipping deployment"